use prost::Message;

pub mod protos {
    // This is generated by prost-build
    include!(concat!(env!("OUT_DIR"), "/xenon.rs"));
}

pub fn pack_4bit(data: &[u16]) -> Vec<u8> {
    let mut packed = Vec::with_capacity((data.len() + 1) / 2);
    for i in (0..data.len()).step_by(2) {
        let high = (data[i] & 0x0F) as u8;
        let low = if i + 1 < data.len() {
            (data[i + 1] & 0x0F) as u8
        } else {
            0
        };
        packed.push((high << 4) | low);
    }
    packed
}

pub fn unpack_16bit(packed: &[u8], len: usize) -> Vec<u16> {
    let mut data = Vec::with_capacity(len);
    for &byte in packed {
        data.push(((byte >> 4) & 0x0F) as u16);
        if data.len() < len {
            data.push((byte & 0x0F) as u16);
        }
    }
    data
}

pub fn save_context(data: &[u16]) -> Vec<u8> {
    let packed = pack_4bit(data);
    let chunk = protos::ContextChunk {
        data: packed,
        length: data.len() as u32,
    };
    let mut buf = Vec::new();
    chunk.encode(&mut buf).unwrap();
    buf
}

pub fn load_context(buf: &[u8]) -> Vec<u16> {
    let chunk = protos::ContextChunk::decode(buf).unwrap();
    unpack_16bit(&chunk.data, chunk.length as usize)
}
